config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  get "/dashboard", to: "pages#dashboard", as: "dashboard"
  get "/dashboard-guide", to: "pages#dashboard_guide", as: "dashboard_guide"
  get "/dashboard/:id", to: "pages#dashboard_booking", as: "dashboard_booking"


  resources :offers, only: [:index, :show, :new, :create]

  resources :slots do
    resources :rentals, only: [:create]
    resources :messages, only: [:create]
  end

  resources :rentals, only: [:create]

  resources :slots, only: [:show]
end

app/views/shared/_card_index.html.erb
<div id="<%= locals[:category_name] %>">
  <div class="cards my-3">
    <% locals[:category].each do |offer| %>
      <%= link_to offer_path(offer) do %>
        <div class="card-category mb-4">
          <% if offer.photos.attached? %>
            <%= cl_image_tag offer.photos.all[0].key, height: 250, class: 'fit-picture' %>
          <% else %>
            <%= image_tag "taj-mahal.png", height: 250, class: 'fit-picture' %>
          <% end %>
          <div class="text mt-3">
            <h3 class="title"><%=offer.title%></h3>
            <p><%=offer.description.truncate(130)%></p>
          </div>
          <div class="card-text">
          </div>
        </div>
      <% end %>
    <% end %>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <div class="brand d-flex align-items-center">
      <%= link_to root_path, class: "navbar-brand" do %>
        <%= image_tag "Logo_couleur.png" %>
      <% end %>
        <h2>EXPLORA WORLD</h2>
    </div>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <div class="search mr-5" style="width:400px;">
          <%= form_tag offers_path, class:'search-form', method: :get do %>
          <%= text_field_tag :query, params[:query], class: "search-term", placeholder: "Find your perfect Visit" %>
          <button type="submit" class="search-button">
            <i class="fa fa-search"></i>
          </button>
           <% end %>
       </div>
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to "Visitor Dashboard", dashboard_path, class: "nav-link mx-4" %>
          </li>
          <li class="nav-item active">
            <%= link_to "Guide dashboard", dashboard_guide_path, class: "nav-link mx-4" %>
          </li>
          <li class="nav-item dropdown">
            <%= cl_image_tag current_user.photo.key, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false  %>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>