config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  get "/dashboard", to: "pages#dashboard", as: "dashboard"
  get "/dashboard-guide", to: "pages#dashboard_guide", as: "dashboard_guide"
  get "/dashboard/:id", to: "pages#dashboard_booking", as: "dashboard_booking"


  resources :offers, only: [:index, :show, :new, :create]

  resources :slots do
    resources :rentals, only: [:create]
    resources :messages, only: [:create]
  end

  resources :rentals, only: [:create]

  resources :slots, only: [:show]
end

app/views/pages/dashboard.html.erb
<div data-controller="maindashboard" class="dashboard-container ">
  <div class="sidebar px-3  d-flex flex-column flex-grow-1 justify-content-between">
    <div class="items my-5">
      <div class="ok text-icon py-2" data-action="click->maindashboard#openTab" data-tab="my-map"> <i class=" icone pe-4 fas  fa-map color-orange"></i><a style ="text-decoration: none;" href="#map_dashboard" data-turbolinks="false">My map</a></div>
      <%# <div class="ok text-icon py-2" data-action="click->maindashboard#openTab" data-tab="my-vod"> <i class=" icone pe-4 fas fa-video color-blue"></i>My vod</div> %>
      <div class="ok text-icon py-2" data-action="click->maindashboard#openTab" data-tab="my-memories"> <i class=" icone pe-4 fas fa-images color-green"></i><a style ="text-decoration: none;" href="#memories" data-turbolinks="false">My memories</a></div>
      <%# <div class="ok text-icon py-2" data-action="click->maindashboard#openTab" data-tab="my-leaderboard"> <i class=" icone pe-4 fas fa-solid fa-graduation-cap color-violet"></i>Leaderboard</div> %>
      <div class="ok text-icon py-2" data-action="click->maindashboard#openTab" data-tab="my-flashcards"> <i class=" icone pe-4 fas fa-copy color-violet "></i><a style ="text-decoration: none;" href="#flashcards" data-turbolinks="false"> My flashcards</a></div>
      <div class="ok text-icon py-2" data-action="click->maindashboard#openTab" data-tab="my-visits"> <i class=" icone pe-4 fas fa-eye color-red"></i><a style ="text-decoration: none;" href="#past_visits" data-turbolinks="false">My past visits</a></div>
      <div class="ok text-icon py-2" data-action="click->maindashboard#openTab" data-tab="my-visits"> <i class=" icone pe-4 fas fa-eye color-blue"></i><a style ="text-decoration: none;" href="#future_visits" data-turbolinks="false">My future visits</a></div>
    </div>
    <div class="explora-profile d-flex flex-column align-items-center mt-2">
      <%= cl_image_tag current_user.photo.key, class: "avatar-bordered", alt: "avatar-bordered" %>
      <h3> <%= current_user.first_name %> </h3>
      <div class="main-wrapper">
        <div class="explora-badge ">
          <div class="badge-circle">
            <i class="fas fa-tree"></i>
              <div class="ribbon">JUNGLER</div>
          </div>
        </div>
      </div>
    </div>


  </div>
  <div class="dashboard-content bg-blue">
    <div class="d-flex w-100 align-items-center justify-content-between  mb-4">

      <div id="map_dashboard" class="whitebox  p-3" style="width:19%;" >
        <p class="text-agregat font-bold"> Planned Visits</p>
        <div class="d-flex justify-content-end">
          <div class="bulle-blue d-flex justify-content-center">
            <div class="count-blue ">
              <%= current_user.rentals.select {|rental| rental.slot.start_at > Date.today}.count %>
            </div>
          </div>
        </div>
      </div>

      <div class="whitebox p-3" style="width:19%;">
        <p class="font-bold"> Past Visits</p>
        <div class="d-flex justify-content-end">
          <div class="bulle-green d-flex justify-content-center">
            <div class="count-green d-flex justify-content-end">
              <%= "#{ current_user.rentals.select {|rental| rental.slot.start_at < Date.today}.count }" %>
            </div>
          </div>
        </div>
      </div>

      <div class="whitebox p-3" style="width:19%;" >
        <p class="font-bold"> Visited Museums</p>
        <div class="d-flex justify-content-end">
          <div class="bulle-red d-flex justify-content-center bg-color-marron">
            <div class="count-red d-flex justify-content-end">
              <%= @museums_visited %>
            </div>
          </div>
        </div>
      </div>

      <div class="whitebox p-3" style="width:19%;" >
        <p class="font-bold"> Visited Monuments</p>
        <div class="d-flex justify-content-end">
          <div class="bulle-violet d-flex justify-content-center">
            <div class="count-violet d-flex justify-content-end">
              <%= @monuments_visited %>
            </div>
          </div>
        </div>
      </div>

      <div class="whitebox p-3" style="width:19%;" >
        <p class="font-bold"> Visited Places</p>
        <div class="d-flex justify-content-end">
          <div class="bulle-orange d-flex justify-content-center">
            <div class="count-orange d-flex justify-content-end">
              <%= @neighborhoods_visited %>
            </div>
          </div>
        </div>
      </div>

    </div>
    <div class="d-flex w-100 justify-content-between mb-2" style="height:600px">

      <%# MAP %>

      <div class="whitebox " style="width:100%;">
        <div id="my-map" class=" d-flex flex-column align-items-center">
          <div class=" map_dashboard" style="width: 100%; height: 600px;"
            data-controller="mapbox"
            data-mapbox-markers-value="<%= @markers.to_json %>"
            data-mapbox-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>"
            data-mapbox-max-zoom-value=15>
          </div>
        </div>
      </div>
    </div>

      <%# PICTURES %>

    <h2 id="memories" class="text-h2">My memories</h2>
      <div class="paul-table whitebox d-flex flex-wrap w-600 align-items-start justify-content-evenly mb-2 p-2">
        <div class="my-3 mx-2 paul-mosaic">
          <div class="d-flex flex-mosaic">
            <% angle = -30 %>
            <% current_user.rentals.select {|rental| rental.slot.start_at < Date.today }.each do |rental| %>
              <% rental.slot.offer.photos[0,2].each do |photo| %>
                <%= cl_image_tag photo.key, height: 300, class: 'paul-picture', style: "transform: rotate(#{angle}deg)" %>
                <% angle += 5 %>
              <% end %>
            <% end %>
          </div>
        </div>
      </div>


      <h2 id="flashcards" class="text-f ">Flashcards</h2>
      <div class="whitebox pt-4 pb-1  w-600 " >
          <div id="my-flashcards" class="" >
            <div class="flashcard d-flex justify-content-between m-5 " >
              <div class="museum ">
                <div class="explora-progress-bar">
                  <span>Museums</span>
                  <span id="progress">20%</span>
                  <div class="progress-wrapper">
                    <div class="progress-input" style="width: 20%;"></div>
                  </div>

                </div>
              </div>
              <div class="monuments">
                <div class="explora-progress-bar">
                  <span>Monuments</span>
                  <span id="progress">30%</span>
                  <div class="progress-wrapper">
                    <div class="progress-input" style="width: 30%;"></div>
                  </div>

                </div>
              </div>
              <div class="Neighborhoods">
                <div class="explora-progress-bar">
                  <span>Places</span>
                  <span id="progress">50%</span>
                  <div class="progress-wrapper">
                    <div class="progress-input" style="width: 50%;"></div>
                  </div>

                </div>
              </div>
            </div>
          </div>
      </div>
    <%# PAST VISIT HERE  %>

    <div id="past_visits" class="past-visit">
     <h2 class="text-h2">Past Visits</h2>
      <div class="whitebox row w-100mb-2 p-2 mx-0">
        <% if @pastvisit.empty? %>
          <p>THERE IS NO PAST VISITS</p>
        <% else %>
          <% @rentals.each do |rental| %>
            <% if (rental.slot.start_at < Date.today) %>
              <div class="card-category my-4 col-3 px-4 d-flex flex-column">
                <%= cl_image_tag rental.slot.offer.photos.all[0].key, height: 250 , class:"img-card", style: "width:100%;"%>
                <div class="text mt-3 flex-grow-1">
                  <h3 class="title"><%= rental.slot.offer.title %></h3>
                  <p><%= rental.slot.start_at.strftime("Visited the %d/%m/%Y")  %></p>
                </div>
                <div class="card-text">
                  <%= link_to "Visit again ?",  offer_path(rental.slot.offer), class: "tab-ghost2", style:"text-decoration:none" %>
                </div>
              </div>
            <% end %>
          <% end %>
        <% end %>
      </div>
    </div>


    <%# FUTURE VISIT HERE  %>

      <h2 id="future_visits" class="text-h2">Future Visits</h2>
      <div class="whitebox row w-600 mb-2 p-2 mx-0">
        <% @rentals.each do |rental| %>
          <% if (rental.slot.start_at > Date.today) %>
            <div class="card-category my-4 col-3 d-flex flex-column">
              <%= cl_image_tag rental.slot.offer.photos.all[0].key, height: 250 , class:"img-card", style: "width:100%;"%>
              <div class="text mt-3">
                <h3 class="title"><%= rental.slot.offer.title %></h3>
                <p><i class="fas fa-calendar-day"></i><%= rental.slot.start_at.strftime(" %d/%m/%Y at %H:%M")  %></p>
              </div>
              <div class="card-text">
                <%= link_to "Go to the live visit !",  slot_path(rental.slot), class: "tab-ghost2", style:"text-decoration:none" %>
              </div>
            </div>
          <% end %>
        <% end %>
      </div>

      <%# FLASHCARDS %>
  </div>
</div>

app/views/pages/dashboard_guide.html.erb
<div data-controller="maindashboard" class="dashboard-container ">
  <div class="sidebar px-3  d-flex flex-column flex-grow-1 justify-content-between">
    <div class="items my-5">
      <div class="ok text-icon py-2" data-action="click->maindashboard#openTab" data-tab="my-map"> <i class=" icone pe-4 fas  fa-map color-orange"></i><a style ="text-decoration: none;" href="#map_dashboard" data-turbolinks="false">My map</a></div>
      <%# <div class="ok text-icon py-2" data-action="click->maindashboard#openTab" data-tab="my-vod"> <i class=" icone pe-4 fas fa-video color-blue"></i>My vod</div> %>
      <div class="ok text-icon py-2" data-action="click->maindashboard#openTab" data-tab="my-memories"> <i class=" icone pe-4 fas fa-images color-green"></i><a style ="text-decoration: none;" href="#memories" data-turbolinks="false">My memories</a></div>
      <%# <div class="ok text-icon py-2" data-action="click->maindashboard#openTab" data-tab="my-leaderboard"> <i class=" icone pe-4 fas fa-solid fa-graduation-cap color-violet"></i>Leaderboard</div> %>
      <div class="ok text-icon py-2" data-action="click->maindashboard#openTab" data-tab="my-flashcards"> <i class=" icone pe-4 fas fa-copy color-violet "></i><a style ="text-decoration: none;" href="#flashcards" data-turbolinks="false"> My flashcards</a></div>
      <div class="ok text-icon py-2" data-action="click->maindashboard#openTab" data-tab="my-visits"> <i class=" icone pe-4 fas fa-eye color-red"></i><a style ="text-decoration: none;" href="#past_visits" data-turbolinks="false">My past visits</a></div>
      <div class="ok text-icon py-2" data-action="click->maindashboard#openTab" data-tab="my-visits"> <i class=" icone pe-4 fas fa-eye color-blue"></i><a style ="text-decoration: none;" href="#future_visits" data-turbolinks="false">My future visits</a></div>
    </div>
    <div class="explora-profile d-flex flex-column align-items-center mt-2">
      <%= cl_image_tag current_user.photo.key, class: "avatar-bordered", alt: "avatar-bordered" %>
      <h3> <%= current_user.first_name %> </h3>
      <div class="main-wrapper">
        <div class="explora-badge ">
          <div class="badge-circle">
            <i class="fas fa-tree"></i>
              <div class="ribbon">JUNGLER</div>
          </div>
        </div>
      </div>
    </div>


  </div>
  <div class="dashboard-content bg-blue">
    <div class="d-flex w-100 align-items-center justify-content-between  mb-4">

      <div id="map_dashboard" class="whitebox  p-3" style="width:19%;" >
        <p class="text-agregat font-bold"> Planned Visits</p>
        <div class="d-flex justify-content-end">
          <div class="bulle-blue d-flex justify-content-center">
            <div class="count-blue ">
              <%= @rentals.select {|rental| rental.slot.start_at > Date.today}.count %>
            </div>
          </div>
        </div>
      </div>

      <div class="whitebox p-3" style="width:19%;">
        <p class="font-bold"> Past Visits</p>
        <div class="d-flex justify-content-end">
          <div class="bulle-green d-flex justify-content-center">
            <div class="count-green d-flex justify-content-end">
              <%= "#{@rentals.select {|rental| rental.slot.start_at < Date.today}.count }" %>
            </div>
          </div>
        </div>
      </div>

      <div class="whitebox p-3" style="width:19%;" >
        <p class="font-bold"> Profit </p>
        <div class="d-flex justify-content-end">
          <div class="bulle-red d-flex justify-content-center bg-color-marron">
            <div class="count-red d-flex justify-content-end">
              <p>10</p>
            </div>
          </div>
        </div>
      </div>

      <div class="whitebox p-3" style="width:19%;" >
        <p class="font-bold"> XXX</p>
        <div class="d-flex justify-content-end">
          <div class="bulle-orange d-flex justify-content-center">
            <div class="count-orange d-flex justify-content-end">
              <%= "XXX" %>
            </div>
          </div>
        </div>
      </div>

    </div>

    <%# All my offers  %>

    <div id="past_visits" class="past-visit">
     <h2 class="text-h2">All my offer</h2>
      <div class="whitebox row w-100mb-2 p-2 mx-0">
        <% if @pastvisit.empty? %>
          <p>You don't have any offer</p>
        <% else %>
          <% @offers.each do |offer| %>
              <div class="card-category my-4 col-3 px-4 d-flex flex-column">
                <%= cl_image_tag offer.photos.all[0].key, height: 250 , class:"img-card", style: "width:100%;"%>
                <div class="text mt-3 flex-grow-1">
                  <h3 class="title"><%= offer.title %></h3>
                </div>
                <div class="card-text">
                  <%= link_to "See details",  offer_path(offer), class: "tab-ghost2", style:"text-decoration:none" %>
                </div>
              </div>
          <% end %>
        <% end %>
        <%= link_to "Create new offer",  new_offer_path(), class: "tab-ghost2", style:"text-decoration:none" %>

      </div>
    </div>


    <%# FUTURE VISIT HERE  %>

      <h2 id="future_visits" class="text-h2">Future Visits</h2>
      <div class="whitebox row w-600 mb-2 p-2 mx-0">
        <% @rentals.each do |rental| %>
          <% if (rental.slot.start_at > Date.today) %>
            <div class="card-category my-4 col-3 d-flex flex-column">
              <%= cl_image_tag rental.slot.offer.photos.all[0].key, height: 250 , class:"img-card", style: "width:100%;"%>
              <div class="text mt-3">
                <h3 class="title"><%= rental.slot.offer.title %></h3>
                <p><i class="fas fa-calendar-day"></i><%= rental.slot.start_at.strftime(" %d/%m/%Y at %H:%M")  %></p>
              </div>
              <div class="card-text">
                <%= link_to "See details",  slot_path(rental.slot), class: "tab-ghost2", style:"text-decoration:none" %>
              </div>
            </div>
          <% end %>
        <% end %>
      </div>

      <%# FLASHCARDS %>
  </div>
</div>

app/views/pages/home.html.erb
<a id="top"></a>
<div class="banner-test w-100 h-100">
  <%= image_tag "Logo_blanco.png", width: 100, height: 100, style: "object-fit: contain; position: absolute; top: 30px; left: 30px;" %>
  <div class="container">
    <div class="d-flex py-5 align-items-center" style="height: 100vh;">
      <div class="w-50 py-5" style="margin-bottom: 50px; color: black;">
        <h1 style="font-size: 65px; margin-bottom: 0px;">
          <span data-controller="typed-js"></span>
        </h1>
        <h2 style="margin-bottom: 30px; font-size: 30px;">Discover the world from your sofa </h2>
        <h3>Save yourself from costly and polluting trips.</h3>
        <h3>Sit comfortably and get ready for a total immersion.</h3>
        <h3>Here, now.</h3>
        <%= link_to "See all offers", offers_path, class: "btn btn-ghost px-5 mt-5", data: {turbolinks: false}%>
      </div>
      <div class="w-50 p-5 position-relative">
        <img class="pictures-banner" src="https://images.unsplash.com/photo-1545126178-862cdb469409?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=387&q=80" alt="" style="position: absolute; top: -263px; left: -20px; width: 380px; height: 394px; object-fit: cover; border-radius: 6px;">
        <img class="pictures-banner" src="https://images.unsplash.com/photo-1524492412937-b28074a5d7da?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1171&q=80" alt="" style="position: absolute; bottom: -102px; right: -42px; width: 390px; height: 327px; object-fit: cover; border-radius: 6px;">
        <img class="pictures-banner" src="https://images.unsplash.com/photo-1567690077111-03ebfbde31bd?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1170&q=80" alt="" style="position: absolute; top: 83px; left: -116px; width: 500px; height: 270px; object-fit: cover; border-radius: 6px;">
      </div>
    </div>
  </div>
</div>
<div style="overflow: hidden">
  <div style="transform: translateY(-135px); transition: 0.3s transform; height: 0px;" data-controller="hpnavbar" data-action= "scroll@window->hpnavbar#display">
  <%= render 'shared/navbar' %>
  </div>
  <div class="container py-5">
    <div class="homepage mb-5">
      <div class="d-flex justify-content-center align-items-center my-5">
        <div class="hp-border-title">....</div>
        <h1 class="hp-title">Let's discover</h1>
        <div class="hp-border-title">....</div>
      </div>
      <p>The Machu Picchu, the MOMA, and a lot more are knocking at your door !</p>
    </div>
    <div class="d-flex justify-content-around pb-5">
      <div class="yellow-card d-flex flex-column justify-content-center align-items-center" style="background-image: linear-gradient(rgba(0,0,0,0.35), rgba(0,0,0,0.35)), url(https://media.vogue.fr/photos/5c8a60d93d44a01271cbef6a/master/w_1600%2Cc_limit/GettyImages-502721407.jpg)">
        <h3 class="yellow-card-shadow title ">MUSEUMS</h3>
        <div class="yellow-card-title-underline mx-3"></div>
        <p class="yellow-card-shadow mx-3">Want to visit every famous museums one by one?</p>
      </div>
      <div class="yellow-card d-flex flex-column justify-content-center align-items-center" style="background-image: linear-gradient(rgba(0,0,0,0.35), rgba(0,0,0,0.35)), url(https://www.batobus.com/sites/default/files/2019-08/stations_05_tour_eiffel_introduction_480x700.png)">
        <h3 class="yellow-card-shadow title ">MONUMENTS</h3>
        <div class="yellow-card-title-underline mx-3"></div>
        <p class="yellow-card-shadow mx-3"> Want to see The Taj Mahal? The Eiffel Tower?</p>
      </div>
      <div class="yellow-card d-flex flex-column justify-content-center align-items-center" style="background-image: linear-gradient(rgba(0,0,0,0.35), rgba(0,0,0,0.35)), url(https://www.nyc.fr/wp-content/uploads/2015/07/times_square.jpg)">
        <h3 class="yellow-card-shadow title ">PLACES</h3>
        <div class="yellow-card-title-underline mx-3"></div>
        <p class="yellow-card-shadow mx-3">Want to discover the streets of New York, or Mexico ?</p>
      </div>
    </div>
  </div>
</div>
<div class="gray-background">
  <div class="container py-5">
    <div class="d-flex justify-content-center align-items-center my-5">
      <div class="hp-border-title">....</div>
      <h1 class="hp-title">They tried Explora World</h1>
      <div class="hp-border-title">....</div>
    </div>
    <div id="carouselExampleControls" class="carousel slide pb-5 mx-auto" style="width: 80%" data-bs-ride="carousel">
      <div class="carousel-inner">
        <%# one %>
        <div class="carousel-item active">
          <div class="review p-5">
            <div class="recommand">
              <h1>"Best experience ever !"</h2>
              <h3>"Seeing the Pyramids was a dream since I was a kid and now it came true ! It was one of the best experience ever !"</h3>
              <div class="icons-grades">
              <%= image_tag "frelon.png", id: "avatar-review" %>
              <a href="#"><i class="fab fa-facebook m-2"></i></a>
              <a href="#"><i class="fab fa-twitter"></i></a>
              <a href="#"><i class="fab fa-google m-2"></i></a>
              </div>
            </div>
            <div class="img-review">
              <div class="card-review" style="background-image: linear-gradient(rgba(0,0,0,0), rgba(0,0,0,0)), url(https://ak.picdn.net/shutterstock/videos/1024420484/thumb/1.jpg)">
              </div>
            </div>
          </div>

        </div>
        <%# two %>
        <div class="carousel-item">
          <div class="review p-5">
            <div class="recommand">
              <h1>"Absolutely stunning"</h2>
              <h3>"Great visit ! I had not travelled for several years but Explora World made me feel like I was on a real trip. I really felt like I was on the streets of Indonesia with a guide ! Thank you !"</h3>
              <div class="icons-grades">
              <%= image_tag "nico.png", id: "avatar-review" %>
              <a href="#"><i class="fab fa-facebook m-2"></i></a>
              <a href="#"><i class="fab fa-twitter"></i></a>
              <a href="#"><i class="fab fa-google m-2"></i></a>
              </div>
            </div>
            <div class="img-review">
              <div class="card-review" style="background-image: linear-gradient(rgba(0,0,0,0), rgba(0,0,0,0)), url(https://img.itinari.com/regions/id-special-region-of-yogyakarta.jpg?ch=DPR&dpr=1&w=1600&s=ee620d84a4303821bfb65f8b7819708f)">
              </div>
            </div>
          </div>
        </div>
        <%# three %>
        <div class="carousel-item">
          <div class="review p-5">
            <div class="recommand">
              <h1>"One word : amazing!"</h2>
              <h3>"Because of global warming, I am really happy I could travel without having to take the plane. The planet and myself are grateful."</h3>
              <div class="icons-grades">
              <%= image_tag "loulou.png", id: "avatar-review" %>
              <a href="#"><i class="fab fa-facebook m-2"></i></a>
              <a href="#"><i class="fab fa-twitter"></i></a>
              <a href="#"><i class="fab fa-google m-2"></i></a>
              </div>
            </div>
            <div class="img-review">
              <div class="card-review" style="background-image: linear-gradient(rgba(0,0,0,0), rgba(0,0,0,0)), url(https://cdn.getyourguide.com/img/location/5ce265372f802.jpeg/88.jpg)">
              </div>
            </div>
          </div>
        </div>
      </div>
      <%# arrow %>
      <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Previous</span>
      </button>
      <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Next</span>
      </button>
    </div>
  </div>

</div>


<div class="container py-5">
  <div class="d-flex justify-content-center align-items-center my-5">
    <div class="hp-border-title">....</div>
    <h1 class="hp-title">Our partners</h1>
    <div class="hp-border-title">....</div>
  </div>
  <div class="partners mb-5">
    <%= image_tag "acro-logo.png", id: "places"%>
    <%= image_tag "london.png", id: "places"%>
    <%= image_tag "kuala.png", id: "places"%>
    <%= image_tag "louvre.png", id: "places"%>
    <%= image_tag "machu-logo.png", id: "places"%>
    <%= image_tag "met-logo.png", id: "places"%>
    <%= image_tag "mexico-logo.png", id: "places"%>
    <%= image_tag "paris-logo.png", id: "places"%>
    <%= image_tag "senso-logo.png", id: "places"%>
    <%= image_tag "syndey-logo.png", id: "places"%>
    <%= image_tag "forbidden-logo.png", id: "places"%>
    <%= image_tag "british-logo.png", id: "places"%>
    <%= image_tag "vatican.png", id: "places"%>
    <%= image_tag "greatwall.png", id: "places"%>
    <%= image_tag "rio.png", id: "places"%>
    <%= image_tag "niagara.png", id: "places"%>
  </div>
</div>