config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  get "/dashboard", to: "pages#dashboard", as: "dashboard"
  get "/dashboard-guide", to: "pages#dashboard_guide", as: "dashboard_guide"
  get "/dashboard/:id", to: "pages#dashboard_booking", as: "dashboard_booking"


  resources :offers, only: [:index, :show, :new, :create]

  resources :slots do
    resources :rentals, only: [:create]
    resources :messages, only: [:create]
  end

  resources :rentals, only: [:create]

  resources :slots, only: [:show]
end

app/models/offer.rb
class Offer < ApplicationRecord
  belongs_to :user
  belongs_to :category

  has_many :slots
  has_many :offers
  has_many :rentals, through: :slots
  has_many :reviews, through: :rentals

  has_many_attached :photos
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?

  validates :address, presence: true
  validates :description, presence: true
  # validates :description, length: { minimum: 10 }
  validates :video_type, inclusion: { in: ["VoD", "Live", "Both"] }
  validates :title, presence: true
  # validates :title, length: { minimum: 5 }
  validates :price, numericality: { greater_than: 0 }
  include PgSearch::Model
  pg_search_scope :search_by_city,
    against: [:city],
    using: {
      tsearch: { prefix: true } # <-- now `superman batm` will return something!
    }
end

app/controllers/offers_controller.rb
class OffersController < ApplicationController
  def index
    @amazonia = Offer.select { |offer| offer.title == "Amazonia" }
    @id = @amazonia[0].id
    if params[:query].present?
      @offers = policy_scope(Offer).search_by_city(params[:query])
    else
      @offers = policy_scope(Offer).all
    end
    @markers = @offers.geocoded.map do |offer|
      {
        lat: offer.latitude,
        lng: offer.longitude,
        image_url: helpers.asset_url("marker.png")
      }
    end
  end

  def show
    @offer = Offer.find(params[:id])
    authorize @offer
    if @offer.geocoded?
    @markers = [
      {
        lat: @offer.latitude,
        lng: @offer.longitude,
        image_url: helpers.asset_url("marker.png")
      }
    ]
    end
  end

  def new
    @offer = Offer.new
    authorize @offer

  end

  def create
    @offer = Offer.new(check_params)
    @offer.user = current_user
    authorize @offer
    if @offer.save
      redirect_to dashboard_guide_path()
    else
      render 'new'
    end
  end

  private

  def check_params
    params.require(:offer).permit(:address, :description, :video_type, :category_id, :city, :title, :price, photos: [])
  end

end

app/views/offers/index.html.erb
<div class="">
  <div class="ps-5">
    <div class="d-flex justify-content-around" id="earth">
      <div data-controller="categories">

        <div class="d-flex">
          <div style="width: 70%;">
            <p class="title-index">All offers</p>

            <div class="tab px-4 mt-2 d-flex justify-content-start">
              <button class="tab-ghost" data-action="click->categories#openTab" data-tab="Museums">Museums</button>
              <button class="tab-ghost" data-action="click->categories#openTab" data-tab="Monuments">Monuments</button>
              <button class="tab-ghost" data-action="click->categories#openTab" data-tab="Neighborhoods">Places</button>
            </div>
            <div class="px-5">
              <%= render "shared/card_index", locals: {category: @offers.select { |offer| offer.category.name == "Museum"}, category_name: "Museums" } %>
              <%= render "shared/card_index", locals: {category: @offers.select { |offer| offer.category.name == "Monument"}, category_name: "Monuments"} %>
              <%= render "shared/card_index", locals: {category: @offers.select { |offer| offer.category.name == "Neighborhood"}, category_name: "Neighborhoods"} %>
            </div>
          </div>
          <div class="position-sticky" style="top: 10vh; height: 90vh; width: 30%; overflow-x:hidden">

            <div style="width: 600px; height: 800px; border-radius: 20px; margin-bottom: 50px;"
              data-controller="mapbox"
              data-mapbox-markers-value="<%= @markers.to_json %>"
              data-mapbox-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>"
              data-mapbox-max-zoom-value=15
              class ="my-3 mx-4 position-sticky d-none"
              id="map_index">
            </div>

            <div id="map" class="mt-0" style="margin-left: -40px; z-index: 1000;" data-markers="<%= @markers.to_json %>" data-amazonia="<%= @id %>">
              <div class="d-flex w-100 align-items-center justify-content-start py-5">
                <div class="df-switch ms-5 me-4">
                  <button type="button" class="btn btn-lg btn-toggle" data-toggle="button" aria-pressed="false" autocomplete="off">
                    <div class="inner-handle"></div>
                    <div class="handle"></div>
                  </button>
                </div>
                <div id="buttons" class="">
                  <input type="button" class="btn-ghost" value="I feel lucky !"><br>
                </div>
              </div>
              <div id="coords"></div>
            </div>
        </div>
      </div>
    </div>
  </div>

</div>

app/views/offers/new.html.erb
<div class="container my-5">
  <div class="d-flex flex-column align-items-center">
    <h2>Create a new offer</h2>
    <!-- app/views/restaurants/_form.html.erb -->
    <%= simple_form_for(@offer)do|f|%>
      <%= f.input :title%>
      <%= f.input :city%>
      <%= f.input :address%>
      <%= f.input :description%>
      <%= f.association :category%>
      <%= f.input :video_type%>
      <%= f.input :price%>
      <%= f.input :photos, as: :file, input_html: { multiple: true } %>
      <%= f.submit%>
    <%end%>
  </div>
</div>

app/views/offers/show.html.erb
<div id="offer_carrousel" class="carousel slide container mt-5" data-bs-ride="carousel">
  <div class="carousel-indicators">
    <% @offer.photos.size.times do |i| %>
    <button type="button" data-bs-target="#offer_carrousel" data-bs-slide-to="<%= i %>" class="<%= "active" if i==0%>" aria-current="<%= "true" if i==0%>" aria-label="Slide <%= i %>"></button>
    <%end%>
  </div>
  <div class="carousel-inner">
    <% @offer.photos.each_with_index do |photo, i| %>
      <div class="carousel-item <%= "active" if i==0%>">
        <%= cl_image_tag photo.key, height: 300, width: 400, class:"d-block w-100" %>
      </div>
    <%end%>

  </div>
  <button class="carousel-control-prev" type="button" data-bs-target="#offer_carrousel" data-bs-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Previous</span>
  </button>
  <button class="carousel-control-next" type="button" data-bs-target="#offer_carrousel" data-bs-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Next</span>
  </button>
</div>


<h3 class="text-center m-5"> <%= @offer.title %></h3>
<div class ="gray-background">
  <div class="d-flex justify-content-between container py-5" data-slots-display-target="description">
    <div class="show-description p-3 flex-grow-1 me-5">
      <div class="d-flex justify-content-between align-items-center">
        <h4 class="mb-0"> Description </h4>
        <p class="visit-type-description">Places</p>
      </div>
      <div class="stars d-flex mb-2">
        <i class="fas fa-star"></i>
        <i class="fas fa-star"></i>
        <i class="fas fa-star"></i>
        <i class="fas fa-star"></i>
        <i class="fas fa-star-half-alt"></i>
      </div>
      <div class="d-flex">
        <i class="fas fa-comment-alt"></i>
        <p class="ms-2">230 reviews</p>
      </div>
      <p class = "mt-2 ms-2"><%= @offer.description %></p>
    </div>
    <div class="show-map flex-shrink-0">
      <div style="width: 100%; height: 400px; border-radius:10px;"
        data-controller="mapbox"
        data-mapbox-markers-value="<%= @markers.to_json %>"
        data-mapbox-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>"
        data-mapbox-max-zoom-value=15>
      </div>
    </div>
  </div>
</div>

<div class="d-flex justify-content-center align-items-center m-5 py-5">
  <div class= "d-flex flex-column align-items-center">
    <%# <h3 class ="mt-3 mb-5">LIVE</h3> %>
      <div class="card-cta card-cta-first-choice ">
        <img src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTw7mZikTnK02y6yEyj1NqcJOQUlya9HJRHrg&usqp=CAU" />
        <div class="card-cta-infos">
          <div>
            <h2><%= @offer.title %></h2>
            <p ><i class="fas fa-check me-1" style="color: #3f51b5"></i></i>Live talk</p>
            <p> <i class="fas fa-check me-1" style="color: #3f51b5"></i></i>Live chat</p>
            <p> <i class="fas fa-check me-1" style="color: #3f51b5"></i></i>Guide's photos</p>
          </div>
        </div>
        <div class="separator-thin">
        </div>
        <div class="card-cta-description">
          <div class="d-flex ms-3 me-3 justify-content-between">
            <p>
              <i class="fas fa-map-marker-alt"></i>
              <%= @offer.city %>
            </p>
            <button class= "btn border-0 shadow-none pt-0 ps-0" data-action="click->slots-display#display" data-bs-toggle="modal" data-bs-target="#staticBackdrop">
            <p><i class="fas fa-calendar-alt"></i> Full schedule
            </button>
          </div>
          <div class = "ms-3 me-3 mb-2 justify-content-between">
            <p>
              <i class="fas fa-calendar-day"></i>
              <%= @offer.slots.all[0].start_at.strftime("%d/%m/%Y at %H:%M") %>
            </p>
          </div>
          <div class="card-cta-separator-thin"></p></div>
          <div class="card-cta-guide py-2 ">
            <p class="ms-3"><strong>Guide</strong></p>
            <div class="d-flex align-items-center ms-3">
              <%= cl_image_tag @offer.slots.all[0].user.photo.key, class: "avatar-bordered card-cta-user" %>
              <%# <img src="https://kitt.lewagon.com/placeholder/users/krokrob" class="card-cta-user avatar-bordered" /> %>
              <div class="ms-2">
                <p><%= "#{@offer.slots.all[0].user.first_name} #{@offer.slots.all[0].user.last_name}"%></p>
              </div>
            </div>
          </div>
          <div class="separator-thin"></div>
          <div class = "d-flex justify-content-center align-items-center card-cta-button">
            <div class="card-cta-price d-flex align-items-center">
              <h2 class="text-white"><%= 5*@offer.price.round %>€</h2>
            </div>
            <button class="card-cta-booking"><%= link_to "Register", slot_rentals_path(@offer.slots.all[0]), method: :post%></button>
          </div>
        </div>
      </div>
  </div>

    <div class= "d-flex flex-column align-items-center">
      <%# <h3 class ="mt-3 mb-5">VOD</h3> %>
        <div class="card-cta card-cta-second-choice ms-4">
          <div class="img" style="background-image: linear-gradient(rgba(95, 64, 64, 0.1), rgba(0, 0, 0, 0.5), rgba(95, 64, 64, 0.1)), url(https://www.cb-expert.fr/wp-content/uploads/2018/03/Couv-Mediametrie-VOD-360-750x440.jpg)"></div>

          <%# <img src="https://www.cb-expert.fr/wp-content/uploads/2018/03/Couv-Mediametrie-VOD-360-750x440.jpg" /> %>
          <div class="card-cta-infos">
            <div>
              <h2><%= @offer.title %></h2>
              <p ><i class="fas fa-check me-1" style="color: #3f51b5"></i></i>Video on demand</p>
            </div>
          </div>
          <div class="separator-thin">
          </div>
          <div class="card-cta-description">
            <div class="d-flex ms-3 me-3 justify-content-between">
              <p>
                <i class="fas fa-map-marker-alt"></i>
                <%= @offer.city %>
              </p>
            </div>
            <div class="ms-3 me-3 mb-2">
              <p>
                <i class="fas fa-clock"></i>
                2h
              </p>
            </div>
            <div class="card-cta-separator-thin"></p></div>
            <div class="card-cta-guide py-1">
              <p class="ms-3"><strong>Guide</strong></p>
              <div class="d-flex align-items-center ms-3">
                <%= cl_image_tag @offer.slots.all[0].user.photo.key, class: "avatar-bordered card-cta-user" %>
                <%# <img src="https://kitt.lewagon.com/placeholder/users/krokrob" class="card-cta-user avatar-bordered" /> %>
                <div class="ms-2">
                  <p><%= "#{@offer.slots.all[0].user.first_name} #{@offer.slots.all[0].user.last_name}"%></p>
                </div>
              </div>
            </div>
            <div class="separator-thin"></div>
            <div class = "d-flex justify-content-center align-items-center card-cta-button">
              <div class="card-cta-price d-flex align-items-center">
                <h2 class="text-white"><%= @offer.price.round %>€</h2>
              </div>
              <button class="card-cta-booking"><%= link_to "Buy", slot_rentals_path(@offer.slots.all[0]), method: :post%></button>
            </div>
          </div>
        </div>

  </div>
</div>

<div class="d-flex justify-content-around gray-background px-3 py-5">
  <div class="show-description p-3" style="height:300px; width: 450px;">
    <h4 class="mt-3 mb-2"> Review from Jimmy </h4>
    <div class="stars  d-flex mb-2 mt-2">
      <i class="fas fa-star"></i>
      <i class="fas fa-star"></i>
      <i class="fas fa-star"></i>
      <i class="fas fa-star"></i>
    </div>
    <br>
    <p class = "mt-2 ms-2"> "Seeing the Pyramids was a dream since I was a kid and now it came true ! It was one of the best experience ever !"</p>
  </div>
    <div class="show-description p-3" style="height:300px; width: 450px;">
    <h4 class="mt-3 mb-2"> Review from Elisa </h4>
    <div class="stars d-flex mb-2 mt-2">
      <i class="fas fa-star"></i>
      <i class="fas fa-star"></i>
      <i class="fas fa-star"></i>
      <i class="fas fa-star"></i>
      <i class="fas fa-star"></i>
    </div>
    <br>
    <p class = "mt-2 ms-2"> "Great visit ! I had not travelled for several years but Explora World made me feel like I was on a real trip. I really felt like I was on the streets of Indonesia with a guide ! Thank you !"</p>
  </div>
    <div class="show-description p-3" style="height:300px; width: 450px;">
    <h4 class="mt-3 mb-2"> Review from Franck </h4>
    <div class="stars d-flex mb-2 mt-2">
      <i class="fas fa-star"></i>
      <i class="fas fa-star"></i>
      <i class="fas fa-star"></i>
      <i class="fas fa-star"></i>
      <i class="fas fa-star"></i>
    </div>
    <br>
    <p class = "mt-2 ms-2"> "Because of global warming, I am really happy I could travel without having to take the plane. The planet and myself are grateful."</p>
  </div>
</div>

<div class="slots-display d-none" data-slots-display-target="slots">
  <h3>Schedule (target : make it appears when clicking on schedule)</h3>
  <% @offer.slots.each do |slot|%>
  <div class="d-flex">
    <div>
      <p> <%= slot.start_at.strftime("Starts : %d/%m/%Y at %H:%M") %> </p>
    </div>
    <div>
      <button> Register </button>

    </div>
  </div>
  <% end %>
</div>

<!-- Modal -->
<div class="modal fade" id="staticBackdrop" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="staticBackdropLabel">Schedule</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <% @offer.slots.each do |slot|%>
        <div class="d-flex justify-content-between">
          <div>
            <p> <%= slot.start_at.strftime("Starts : %d/%m/%Y at %H:%M") %> </p>
          </div>
          <div>
            <button class="btn btn-primary"> Register </button>
          </div>
        </div>
        <% end %>
      </div>
      <div class="modal-footer">
      </div>
    </div>
  </div>
</div>